### ISSUE TITLE
JsonParserSpecJvm is failing

### ISSUE THREAD

**Issue by SethTisue** [spray/spray-json#315]
this turned up in the Scala 2.12 community build, but it's reproducible outside of dbuild, just clone the rep and run `sbt sprayJsonJVM/test` and you get

```
[info] JsonParserSpecJvm
[info] The JsonParser (on the JVM) should
[info]   + be reentrant
[error]   x fail gracefully for deeply nested structures
[error]    'stackoverflow' != 'nonfatal: JSON input nested too deeply:JSON input was nested more deeply than the configured limit of maxDepth = 200' (JsonParserSpecJvm.scala:67)
[error] Actual:   stackoverflow
[error] Expected: nonfatal: JSON input nested too deeply:JSON input was nested more deeply than the configured limit of maxDepth = 200
```

**Comment by SethTisue** [comment]
@jrudolph sequel to #304?

**Comment by jrudolph** [comment]
It doesn't fail on my machine. It failed on Travis so I adapted the bounds a bit so now it passed on Travis as well. I guess on some JVMs it might still fail. Let's make the bounds a little more lose again.

**Comment by jrudolph** [comment]
Hopefully fixed in #316.

**Comment by SethTisue** [comment]
it still failed at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk11-integrate-community-build/694/consoleFull
